# ref: https://argoproj.github.io/argo-workflows/artifact-repository-ref/

apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: argo  
  annotations: 
    workflows.argoproj.io/default-artifact-repository: default-v1
data:
  default-v1: |
    gcs:
      endpoint: storage.googleapis.com
      bucket: mlops-ai-platform-nwd
      region: asia-northeast3
      insecure: true