# Tested on Seldon Core: v1.8.0
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: nwd-segmentation
  namespace: seldon
spec:
  name: nwd-segmentation-model
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/tfserving-proxy:1.8.0
          name: tfserving-proxy
        - image: tensorflow/serving:2.4.1-gpu
          name: tfserving
          args:
          - --port=2000
          - --rest_api_port=2001
          - --model_name=segmentation
          - --model_base_path=/mnt/models
          ports:
          - containerPort: 2000
            protocol: TCP
          - containerPort: 2001
            protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
              nvidia.com/gpu: 1
          volumeMounts:
           - mountPath: /mnt/models
             name: tfserving-provision-location
             readOnly: true
    graph:
      children: []
      modelUri: pvc://nfs-pv-claim/seldon-model/nwd
      implementation: TENSORFLOW_SERVER
      name: tfserving-proxy
      parameters:
        - name: signature_name
          type: STRING
          value: serving_default
        - name: model_name
          type: STRING
          value: nwd
    name: default
    replicas: 1
