apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: nwd-segmentation
  namespace: seldon
spec:
  name: nwd-segmentation-model
  predictors:
  - graph:
      children: []
      implementation: TENSORFLOW_SERVER
      modelUri: pvc://nfs-pv-claim/seldon-model/nwd
      name: segmentation
      parameters:
        - name: signature_name
          type: STRING
          value: serving_default
        - name: model_name
          type: STRING
          value: nwd
    name: default
    replicas: 1
