apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pv-claim
  namespace: 'seldon'
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: "nfs-pv-seldon"
  resources:
    requests:
      storage: 200Gi
