apiVersion: v1
data:
  configManagementPlugins: |
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
  repositories: |
    - type: git
      url: https://github.com/lunarbridge/nwd-cluster-resources
    - type: git
      url: https://github.com/lunarbridge/nwd-pipeline-continuous-training
kind: ConfigMap
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd