# ref: https://github.com/kubeflow/pipelines/issues/3313
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-argo
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/data-storage/nfs-share
    server: nfs-server
