# This is a basic workflow to help you get started with Actions

name: Create continuous training workflow template

# Controls when the action will run. 
on:
  push:
    paths:
      - 'pipeline/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with: 
          python-version: '3.9'
          architecture: 'x64'
        
      - name: Install dependencies
        run: |
          python -m pip install -r pipeline/requirements.txt
          
      - name: Generate workflow template
        run: |
          python -c "import pipeline; pipeline.create_continuous_training_workflow()"
          
      - name: Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Push by github actions
